services:
  gym_db:
    container_name: "dbgym-gym_db"
    environment:
      POSTGRES_DB: "${GYM_DB_NAME}"
      POSTGRES_PASSWORD: "${GYM_DB_PASS}"
      POSTGRES_USER: "${GYM_DB_USER}"
    image: "postgres:15"
    volumes:
      - "gym_db:/var/lib/postgresql/data"

  trainer:
    build:
      context: "trainer"
    container_name: "dbgym-trainer"
    depends_on:
      - "gym_db"
    environment:
      GYM_DB_NAME: "${GYM_DB_NAME}"
      GYM_DB_PASS: "${GYM_DB_PASS}"
      GYM_DB_USER: "${GYM_DB_USER}"
      TRAINER_PORT: "${TRAINER_PORT}"
      TRAINER_PG_NAME: "${TRAINER_PG_NAME}"
      TRAINER_PG_PASS: "${TRAINER_PG_PASS}"
      TRAINER_PG_PORT: "${TRAINER_PG_PORT}"
      TRAINER_PG_USER: "${TRAINER_PG_USER}"
    ports:
      - "${TRAINER_PORT}:${TRAINER_PORT}"
      - "${TRAINER_PG_PORT}:${TRAINER_PG_PORT}"
    shm_size: "48gb"
    volumes:
      - "trainer:/trainer"
      - "tpch_sf1:/tpch_sf1"
      - "tpch_sf10:/tpch_sf10"

  monitor:
    build:
      context: "monitor"
    container_name: "dbgym-monitor"
    depends_on:
      - "trainer"
    environment:
      GYM_DB_NAME: "${GYM_DB_NAME}"
      GYM_DB_PASS: "${GYM_DB_PASS}"
      GYM_DB_USER: "${GYM_DB_USER}"
      MONITOR_PORT: "${MONITOR_PORT}"
    ports:
      - "${MONITOR_PORT}:${MONITOR_PORT}"

  dbgym:
    build:
      context: "dbgym"
    container_name: "dbgym-dbgym"
    depends_on:
      - "trainer"
    environment:
      HOSTNAME: "${HOSTNAME}"
      GYM_DB_NAME: "${GYM_DB_NAME}"
      GYM_DB_PASS: "${GYM_DB_PASS}"
      GYM_DB_USER: "${GYM_DB_USER}"
      TRAINER_PORT: "${TRAINER_PORT}"
      TRAINER_PG_NAME: "${TRAINER_PG_NAME}"
      TRAINER_PG_PASS: "${TRAINER_PG_PASS}"
      TRAINER_PG_PORT: "${TRAINER_PG_PORT}"
      TRAINER_PG_USER: "${TRAINER_PG_USER}"
    volumes:
      - "dbgym:/dbgym"
      - "tpch_queries:/tpch_queries"
      - "tpch_schema:/tpch_schema"
    profiles:
      - "gym"

#  nyoom:
#    build:
#      context: "nyoom"
#    container_name: "dbgym-nyoom"
#    depends_on:
#      - "monitor"
#    environment:
#      GYM_DB_NAME: "${GYM_DB_NAME}"
#      GYM_DB_PASS: "${GYM_DB_PASS}"
#      GYM_DB_USER: "${GYM_DB_USER}"

volumes:
  dbgym: {}
  gym_db: {}
  trainer: {}
  tpch_schema:
    external: true
  tpch_sf1:
    external: true
  tpch_sf10:
    external: true
  tpch_queries:
    external: true